#!/usr/bin/env bash
# crowdsec-whitelist.sh — install a CrowdSec whitelist so legit UniFi traffic
# (device check-ins + Tailscale admin) is never banned on an exposed frontend.
#
# Writes a s02-enrich parser and reloads CrowdSec. Run on the host that runs
# CrowdSec — which must sit at the reverse proxy in front of the exposed UniFi
# frontend for the bouncer to actually enforce.
#
# Usage:
#   sudo ./crowdsec-whitelist.sh [--apply] [--controller-ip IP] [--cidr CIDR]...
#
#   (no flags)        print the whitelist YAML to stdout
#   --apply           write it to the parser dir and reload crowdsec
#   --controller-ip   controller/inform IP to exempt (default: 69.169.98.98)
#   --cidr CIDR       extra CIDR to exempt; repeatable (default incl. Tailscale)
set -euo pipefail

dest="/etc/crowdsec/parsers/s02-enrich/unifi-whitelist.yaml"
controller_ip="69.169.98.98"
cidrs=("100.64.0.0/10") # Tailscale CGNAT
apply=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --apply) apply=1; shift ;;
    --controller-ip) controller_ip="${2:?}"; shift 2 ;;
    --cidr) cidrs+=("${2:?}"); shift 2 ;;
    -h | --help)
      sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "error: unknown arg: $1" >&2
      exit 1
      ;;
  esac
done

render() {
  cat <<EOF
name: ghostctl/unifi-whitelist
description: "Whitelist UniFi mgmt/inform + Tailscale so legit traffic is never banned"
# Generated by crowdsec-whitelist.sh.
whitelist:
  reason: "UniFi controller management, inform sources, and Tailscale"
  ip:
    - "${controller_ip}"
  cidr:
EOF
  for c in "${cidrs[@]}"; do
    printf '    - "%s"\n' "$c"
  done
}

if ((apply == 0)); then
  render
  echo
  echo "# Re-run with --apply (as root) to write ${dest} and reload crowdsec." >&2
  exit 0
fi

if [[ $EUID -ne 0 ]]; then
  echo "error: --apply needs root (writes ${dest})" >&2
  exit 1
fi

mkdir -p "$(dirname "$dest")"
render >"$dest"
echo "Wrote $dest"

if command -v systemctl >/dev/null 2>&1; then
  systemctl reload crowdsec && echo "Reloaded crowdsec."
else
  echo "systemctl not found — reload crowdsec manually to apply."
fi
